### ISSUE TITLE
Youtube - Can't stop video after clicking on progress bar before actually playing the video

### ISSUE THREAD

**Issue by ChristianPV** [Selz/plyr#105]
Hi, i think i have found a problem with the youtube player. Here are the steps for reproducing it.

1. Open plyr.io
2. Click on Youtube Tab.
3. Click on progress bar without starting the video.
4. Try to stop the video.
5. ???.

Browser: IE11. Google Chrome, and Firefox Latest version. Windows 8.1.

**Comment by SamPotts** [comment]
Dang. I'll take a look.

**Comment by calvintam236** [comment]
@ChristianPV You can stop/resume by clicking the screen. The button is not working nor reflecting the player status.

**Comment by SamPotts** [comment]
@calvintam236 @ChristianPV Seems to be a bug with the YouTube API. I'll see if I can find a workaround. 

![screen shot 2015-08-03 at 9 05 01 pm](https://cloud.githubusercontent.com/assets/719092/9036288/6fa67ef4-3a23-11e5-9bbd-50d6edacb04c.png)

**Comment by ChristianPV** [comment]
@calvintam236 I know you can do that but should the user do that and why should they? it's not expected behaviour and not their responsability to look for workarounds. @SamPotts How is it going? If it's a youtube bug, i think we could hide the progress bar until the user starts the video. What do you think?

**Comment by calvintam236** [comment]
@ChristianPV My comment is a workaround until the issue being fixed, and also part of troubleshoot.. I do not think it should hide the progress bar because a lot of people seek the video to a point instead of the beginning.
@SamPotts YouTube just updated their HTML5 player in the website. The controls background are now transparent :) Should have changes to API as well. http://www.engadget.com/2015/08/04/youtube-rolls-out-new-html5-player/

**Comment by ChristianPV** [comment]
I found out that you can not click the button that forwards the video for 10 seconds, as it currently restarts the video. @ Calvintam236 I understand that it is an interim solution but your suggestion puts two buttons unusable vs none with what I am suggesting. The user can search the video to a point after clicking play.

**Comment by SamPotts** [comment]
I've been working on it when I can but basically the issue is that their `onStateChange` callback does not fire when you seek before you start playback. This basically breaks the script from that point onwards. We're not alone...
https://code.google.com/p/gdata-issues/issues/detail?id=4706

**Comment by calvintam236** [comment]
@SamPotts Updating @ChristianPV's last comment. It cannot seek the video to a particular point when the video has seeked before starting. I believe it is the same root cause.

@ChristianPV My previous comment is not a suggestion. ```My comment is a workaround until the issue being fixed, and also part of troubleshoot..```

**Comment by calvintam236** [comment]
@SamPotts @ChristianPV I just created a pull request to fix the events are not fired and video cannot seek before video started.

I notice other issues like keyboard control in YouTube player is different than plyr itself. I don't know @SamPotts is willing to match the keyboard control or just disable it (adding disablekb: 1 in YT object). Right now, when you use arrows to seek, the progress does not update.

**Comment by SamPotts** [comment]
Thanks @calvintam236 , I'll take a look at your pull request and give it a test. 

I wouldn't add arrow support into the core library since it is ok on YouTube.com as a concept because each video has it's own page so there's no chance of two players being present whereas with Plyr that's not the case. The arrow keys *will* work when you are focused on the progress bar, as is the default behaviour for the `<input type='range'>` element. If you wanted the arrow keys to seek the player when not focused on the progress, I'd suggest binding to the document and using the API functions to do so.

**Comment by calvintam236** [comment]
To fix @ChristianPV issue completely, plyr should not start the video after seeking. No such issue on Youtube.com player though.

**Comment by SamPotts** [comment]
This is the default behaviour of the YouTube API unfortunately. Calling `.seekTo` in their API will automatically play the video.

**Comment by SamPotts** [comment]
Thanks to @calvintam236 for your help with this :+1: Looks to be all resolved now.

**Comment by ChristianPV** [comment]
@calvintam236 Thanks for solving this!! :+1:
