### ISSUE TITLE
Missing SVG elements when the <base> tag is in use

### ISSUE THREAD

**Issue by sven-er** [Selz/plyr#127]
hi,

I have the same problem like here: https://github.com/Selz/plyr/issues/91 all the SVG icons are missing.
i found out that the problem is the base tag on my Page, for more Info look here http://stackoverflow.com/a/18265336/796152 

I have to use additional JS like the svgfixer.js to solve the problem -> https://gist.github.com/leonderijke/c5cf7c5b2e424c0061d2

Do you think it's possible to integrate an additional  config or a check for this in plyr directly?

**Comment by SamPotts** [comment]
Will add something for this to the next release :+1:

**Comment by SamPotts** [comment]
Actually looking at this, I think this is something the dev should handle at their end rather than including in the code, since the loading of the SVG is really just an example of how it can be done. You should bundle the icons with any other svg icons as part of your build and manage them outside of the plugin. This is what we do with Plyr at Selz.com.

**Comment by gino8080** [comment]
Could you please show an example of using self icons or plain css icon?

thank you!

**Comment by SamPotts** [comment]
Self hosted SVG sprite you mean or using icon fonts? I'd advise against icon fonts but if you must use them you'd have to create custom controls and pass them to the plugin. More details are here:
https://github.com/Selz/plyr/blob/master/controls.md
Just replace any `<svg>` with your icon font `<span>` or whatever.
