### ISSUE TITLE
Making changes / building

### ISSUE THREAD

**Issue by gurupras** [Selz/plyr#133]
I'd like to make changes to the CSS to change the background color of the controls.
I see that the CSS itself is split up between LESS and SASS. I'm new to web development and I have no idea on how to build these to generate (unminified) CSS.

Could you please add instructions or point me in the right direction so that I can achieve this?

**Comment by SamPotts** [comment]
Hey @gurupras , the LESS or SASS (you only need one) must be processed into CSS for any changes you make. There's a few ways to do this depending on your environment: 
- Gulp / Grunt - Node/JavaScript based built tools
- Codekit - Desktop mac app for building many languages
- Dotless - A nuget package for c#/.NET builds
... and many more

It really depends on your workflow. If you're new to LESS or SASS, I'd probably recommend SASS at this point since it's more advanced. I'm yet to make the switch over.

**Comment by SamPotts** [comment]
Just closing this as an issue. Feel free to reply if you have questions still.
