### ISSUE TITLE
WebM without duration in header

### ISSUE THREAD

**Issue by ronag** [Selz/plyr#164]
Our server generates WebM files without a duration in the header, because it is streamed. However, we do know the duration.

Is there anyway we can manually provide the duration to plyr? Either through e.g. `Content-Duration` header or a property on the javascript object?

**Comment by SamPotts** [comment]
I could definitely add it as an option to pass in. I'll look into it. :+1:

**Comment by ronag** [comment]
@SamPotts: Thanks!

**Comment by kolpax** [comment]
+1

**Comment by ronag** [comment]
@SamPotts: Any update on this? Or maybe I could get some hints what the relevant places to fix this are and I can try adding it myself.

**Comment by SamPotts** [comment]
I did start at the weekend but the problem is that the duration property of a media element is only a getter so setting it won't be possible meaning I'll have to abstract it to to another variable somehow. Should be fine, I'll create a 'getDuration' method which will return the custom duration (if specified) or the determined duration. I'll take a look again tonight.

**Comment by SamPotts** [comment]
Hey, sorry for the delay with this. You can now add a duration option either using the usual options object or using a data attribute (`data-plyr`) which I just added support for, obviously it needs to be JSON formatted so you need to wrap the JSON in single quotes in your markup. 

https://github.com/Selz/plyr/blob/master/readme.md#options

**Comment by ronag** [comment]
@SamPotts: Awesome! Thanks.
