### ISSUE TITLE
Multiple instances of plyr in IE 11 

### ISSUE THREAD

**Issue by dostaljak** [Selz/plyr#172]
After the initialization of the player, only the last matching div on a page is actually affected. This problem is only in IE 11 and lower.

**Comment by Ambroos** [comment]
Hi! It seems to have something to do with relying on CustomEvent. IE doesn't support it properly (Edge does). Adding the CustomEvent polyfill found [here](https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/CustomEvent#Polyfill) is a good temporary workaround until this gets fixed in Plyr itself.

**Comment by SamPotts** [comment]
Hey guys, sorry this was missed in my testing. It's strange that it's throwing an error. I did add a `CustomEvent` polyfill but didn't realise that the issue with IE is that `CustomEvent` is an object when it should be a function so the check should be more specific like the MDN polyfill. 

I'll update it now.
