### ISSUE TITLE
Need double click to play audio

### ISSUE THREAD

**Issue by tskkh** [Selz/plyr#190]
Hi,
First of all thanks for this great plugin. Now I'm trying to change the media source when user click to play audio, the media src are changed but when I click button play first time it won't play , it need double click on that button. Does I did something wrong?

This is my code:

```  
var player = plyr.setup({
        controls: ["play", "current-time","mute","volume"],
        displayDuration: false,
        hideControls: true,
        tooltips: { controls: false, seek: false },
        click: false
      });

      $.each(player, function( index, value ) {
        value.media.addEventListener('play', function(event) {
            value.source({
              type:       'audio',
              title:      'Example title',
              sources: [{
                src:      'https://cdn.selz.com/plyr/1.5/Kishi_Bashi_-_It_All_Began_With_a_Burst.mp3',
                type:     'audio/mp3'
              },
              {
                src:      'https://cdn.selz.com/plyr/1.5/Kishi_Bashi_-_It_All_Began_With_a_Burst.mp3',
                type:     'audio/ogg'
              }]
            });
        });
      });

```

**Comment by SamPotts** [comment]
Thanks for reporting this. I'll take a look into it this weekend. Cheers :+1:

**Comment by makeitTim** [comment]
It looks like you are only setting the source when the "play" event is called. So, it setups with no source. You press play the first time, it calls the event play event (even though it has nothing to play, so it probably shouldn't be calling the event?) then it loads your sources. You have to press play again to play the newly loaded sources. Should be able to fix by removing the ... addEventListener('play' ... line and its closing, assuming it otherwise is right.

**Comment by SamPotts** [comment]
Sorry I admit I didn't look at the code snippet the first time around. Remove it from the event listener and it should work as expected.
