### ISSUE TITLE
After escaping fullscreen, the browser moves to the top of the page

### ISSUE THREAD

**Issue by Kommandat** [Selz/plyr#236]
If you scroll down to watch a video, enter full screen, and then escape fullscreen, the browser moves to the top of the page. This isn't desirable since it would be an annoyance for the user to scroll all the way back down to where they were.

If possible I would like to work on fixing this bug. I'm looking for some things to work on over the summer and this project looks interesting! Let me know if that's cool with you and if you have any advice on where I can get started.

**Comment by SamPotts** [comment]
My only concern is that the full screen functionality uses the native behavior and API. Changing that can sometimes be a bit iffy. If there's an option related to the standard full screen API, that would be preferable.

**Comment by Kommandat** [comment]
I was able to fix the bug without changing things around too much. Basically, I saved the scrollbar position before entering fullscreen and then restored the scrollbar position after exiting fullscreen. It's a bit janky and it doesn't work on Safari. It does work on Chrome and Firefox.

I've attached my modified plyr.js (as a .txt because I can't upload .js). Let me know what you think and maybe with some improvements we can fix the bug. You can find my changes in lines 171-172, 1950-1953 and 2000-2003.

[plyr.txt](https://github.com/Selz/plyr/files/276242/plyr.txt)

PS: This seems like a pretty common issue among web video players. Check this out: https://bugs.chromium.org/p/chromium/issues/detail?id=142427.

**Comment by SamPotts** [comment]
Yeah I mean like I say, it's going to be common with any full screen element since plyr just uses the regular full screen API. Will take a look shortly. Currently on my way to the UK. 

Sam

**Comment by Kommandat** [comment]
Even if plyr uses the regular full screen API, I think it would be best to fix an issue that the regular full screen has, just so plyr is better. Sounds good!

**Comment by SamPotts** [comment]
Merged in latest version

**Comment by raulbarriga** [comment]
> I was able to fix the bug without changing things around too much. Basically, I saved the scrollbar position before entering fullscreen and then restored the scrollbar position after exiting fullscreen. It's a bit janky and it doesn't work on Safari. It does work on Chrome and Firefox.
> 
> I've attached my modified plyr.js (as a .txt because I can't upload .js). Let me know what you think and maybe with some improvements we can fix the bug. You can find my changes in lines 171-172, 1950-1953 and 2000-2003.
> 
> [plyr.txt](https://github.com/Selz/plyr/files/276242/plyr.txt)
> 
> PS: This seems like a pretty common issue among web video players. Check this out: https://bugs.chromium.org/p/chromium/issues/detail?id=142427.

This is the [link](https://stackoverflow.com/questions/60474901/restore-scroll-position-after-toggled-a-modal-in-react-with-usecontext) I used to save the scroll position and go back to it for my project. I had a carousel image modal with a fullscreen expand button but when I exited the fullscreen and then exited the modal, I would find myself at the top of the page instead of the location where I had opened the modal up.

Essentially, before calling `setIsOpen(true);` to open the modal, I called `setScrollPosition(window.pageYOffset);` to save the window position. Then after I interacted with fullscreen, opened and closed the modal I call `window.scrollTo(0, scrollPosition);` and then `setIsOpen(false);` to close the modal. 

This works perfectly. So simple, no need for other packages. Maybe this can be added to the config for this package in order to deal with this behavior.
