### ISSUE TITLE
Support of .avi ?

### ISSUE THREAD

**Issue by JauCarre** [Selz/plyr#255]
À quand le support des vidéos de type .avi ?

**Comment by AnthyG** [comment]
Short answer: No.
The reason here is that Plyr does actually just uses the HTML5-Video-Tag (As far as I know). And that only supports MP4, WebM and Ogg.
Just use an online converter or so, to convert your .avi file(s) to MP4 or one of the other two, or both :wink: 

Here'sa link to a good website explaining the Video Tag:
http://www.w3schools.com/html/html5_video.asp

**Comment by SamPotts** [comment]
As above basically; no. 

👎 for a link to w3schools though @AnthyG haha! I prefer MDN:
https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats

Plyr also has an API method for checking support for a mime type:
https://github.com/Selz/plyr#api

See `support()` - it requires a mime type such as `video/mp4`. Here's the source:
https://github.com/Selz/plyr/blob/master/src/js/plyr.js#L244

**Comment by SamPotts** [comment]
Also, if you're on a Mac, I'd recommend Handbrake for quick re-encoding of videos.
