### ISSUE TITLE
current time goes back to 00:00 after one hour

### ISSUE THREAD

**Issue by TheHiddenHaku** [Selz/plyr#280]
Hello. I found this issue.
Usually we have very short video, but recently we had to show a video that is almost 5 hours long.
When the elapsed time reaches 59:59 in goes back to 00:00.
Is there a way to display the hours too?

Here a visual example of what i mean. 1h 8m 36s were passed, but the player display only 08:36
![IScreen](https://dl.dropboxusercontent.com/u/2710062/githubIssues/Screenshot-2016-06-17-11-55-40.png)

**Comment by SamPotts** [comment]
Hmm that screenshot looks like an old version of Plyr. This issue was fixed a while ago.  If you try the latest version (you'll need to update CSS too) then you'll see it works fine: 

![screen shot 2016-06-25 at 10 57 50 pm](https://cloud.githubusercontent.com/assets/719092/16356829/8ed6374a-3b28-11e6-9638-c037c40a6225.png)
