### ISSUE TITLE
Can not click on button controls with iPad (iOS 9)

### ISSUE THREAD

**Issue by ericleroy01** [Selz/plyr#391]
how to reproduce
1. play video (controlbar is hidden)
2. click on vidéo (control bar is displayed)
3. Attempt to click on volume, pause or fullscreen button does not work

**Comment by Parasoul** [comment]
+1

**Comment by sparkktv** [comment]
I have the same issue on my iPad Pro 12 using this player with Youtube. The Youtube watermark blocks the fullscreen and volume controls, when you attempt to go full screen you end up hitting the Youtube watermark and opening Youtube.

**Comment by SamPotts** [comment]
What version of Plyr are you guys using? It's not ideal but Vimeo and YouTube don't currently have full UI support due to an issue with iOS and `<iframe>`s:
https://github.com/Selz/plyr/issues/183

I'm looking into whether I can improve this somehow...

**Comment by ericleroy01** [comment]
hi,


I used plyr.io on my iPad 3


Envoyé de mon S7 Edge via Outlook Mobile






On Sat, Nov 19, 2016 at 3:46 PM +0100, "Aaron Bielert" <notifications@github.com> wrote:












I have the same issue on my iPad Pro 12 using this player with Youtube. The Youtube watermark blocks the fullscreen and volume controls, when you attempt to go full screen you end up hitting the Youtube watermark and opening Youtube.

**Comment by sparkktv** [comment]
Latest Version...

**Comment by SamPotts** [comment]
OK what type of video are are we talking about here? This is why it helps to put as much detail into the issues as possible. I wrote a template to help but people seem incapable of filling it out and instead delete it all and replace it with vague details. 

YouTube and Vimeo are currently not supported so you will get the native embed UI on iOS. This is because, for whatever reason, programmatically playing the video via API does not work and iOS wants a click of the iframe instead. This may have changed in iOS 10 so I'm looking into it.

**Comment by sparkktv** [comment]
I'm on iOS 10 using Youtube. Full Screen doesn't work with any custom player, I know that for a fact as so far Plyr is the only one that works full screen because it uses the YT player on iOS. But the watermark is covering the buttons to control the volume & full screen. And I'm having the same issue as the thread starter, the controls keep disappearing and when you click it pauses the video.

**Comment by SamPotts** [comment]
Can you try this again in the latest version? I think it should be fixed. Re-open if not. I've re-enabled YouTube on iPad with iOS10 + as it seems to work ok now.

**Comment by sparkktv** [comment]
Works perfect now, thank you so much...
