### ISSUE TITLE
Some suggested CSS for Play button outline

### ISSUE THREAD

**Issue by onigetoc** [Selz/plyr#413]
Some suggested CSS for Play button outline
Play button hand cursor.
border radius and no border radius fulllscreen
```
.plyr *:focus {
    outline: 0 !important;
}
.plyr__play-large {
    cursor: pointer;
}
.plyr {
    border-radius: 6px
}
.plyr--fullscreen-active {
    border-radius: 0
}
```

**Comment by SamPotts** [comment]
Thanks for the suggestions but removing outline for focus styles without a suitable replacement is a no no. You have to consider visually impaired users as well as your annoyance by the dotted outline. So that stays. 

http://www.outlinenone.com/

The `cursor: pointer` I could add but given it's parent already has that style, it's inherited. 

The border radius is a personal preference. The default styles don't include it so you can add/remove this as you want.

**Comment by onigetoc** [comment]
Hi, on the demo i downloaded, The big Play button do not have cursor pointer.
For the outline i will remove it with my own CSS.

**Comment by SamPotts** [comment]
Twitter video doesn't look like Plyr. Facebook does since their redesign though.  Anyhow, that's the power of CSS. You can make it look how you like. Go for it 👍 

With regards to font icons. I'll not being going backwards from SVG. I'd suggest you do some reading:

- https://css-tricks.com/icon-fonts-vs-svg/
- https://www.sitepoint.com/icon-fonts-vs-svg-debate/

SVGs are designed to be used as icons etc. They are perfect for the job. Using a font is a *hack*.

**Comment by onigetoc** [comment]
I know but even Videojs use Fonts icon now. 
I don't want to be rude but did you look at the Twitter video player?
https://twitter.com/mashable/status/792542311662047232

**Comment by SamPotts** [comment]
Videojs is hardly the benchmark to go by. If you want to use outdated technology that was never designed for the job, then use videojs or write your own "old tech" skin for Plyr. SVG is the future, you just haven't realised it yet :) 

One button does not make the whole UI the same 👍

**Comment by onigetoc** [comment]
Ok, this is a comparison.
https://jsfiddle.net/onigetoc/c4pgmp8r/4/

**Comment by SamPotts** [comment]
OK I get it. You don't like the appearance. Change the CSS then. Done.
