### ISSUE TITLE
use Font Awesome Icons instead of SVG

### ISSUE THREAD

**Issue by Suxiaogang** [Selz/plyr#51]
Thank you for the simple but cool jobs ~

And it woild be great if font-awesome icons are optional for the controls icons.
http://fontawesome.io/icons/#video-player

**Comment by SamPotts** [comment]
Without going into too much detail, SVG is my preferred option now. Icon webfonts often don't look as crisp. If you're set on using fontawesome, I'd suggest using custom controls using the `html` parameter.

For more info on why SVG is better:
https://css-tricks.com/icon-fonts-vs-svg/

**Comment by dzcpy** [comment]
Font awesome 5 has an SVG version now, which each of the icons can be imported individually. Check https://www.npmjs.com/package/@fortawesome/free-solid-svg-icons.

**Comment by sampotts** [comment]
I’m happy with the current icons but you’re welcome to use whatever icons you like in your implementation 👍

**Comment by aubreyz** [comment]
Plyr is great -- but I think it would be good (and would get more traction for this great plugin) if, when folk asked questions, the gurus out there gave a bit of a coding hint instead of sending folk off reading. I have been reading and reading and still have no clue as to how to do in practice what the OP here asks.  How exactly do I get a font element into a button?

I think the reason to do this is more pressing than the desirability of the particular SVG icons used - rather it has to do with a) the speed of page loading where a font is already being used and b) consistency of icons across a page.  

Any help to actually do this would be much appreciated. I ask having done a lot of reading with no greater insight.
