### ISSUE TITLE
how to use this player

### ISSUE THREAD

**Issue by taug** [Selz/plyr#52]
I can not find the dir "//cdn.plyr.io/1.0.19" needed in file "docs/index.html".

**Comment by SamPotts** [comment]
That isn't a directory, it's a protocol relative URL. The docs index is purely meant as an example usage of the player. `<script src="//cdn.plyr.io/1.0.19/plyr.js"></script>` will pull the JavaScript source from the CDN for example. 

In terms of a how to, I'd suggest starting with the readme.md.

**Comment by taug** [comment]
Oh,thank you.But when I open the "index.html" in my browser,I looks like this:
![2015-03-04 17 13 56](https://cloud.githubusercontent.com/assets/5243670/6480751/0d978446-c292-11e4-8443-8383db053d22.png)

**Comment by SamPotts** [comment]
Hey there, yes that's because you're serving it from the local filesystem. Looks like you're using Ubuntu which comes with Apache so you should use that for local development. I'm pretty sure the root directory for Apache is `/var/www/html` so you can create a `plyr` folder in there and put all the assets into it. Then go to `http://localhost/plyr` and it should work.

**Comment by taug** [comment]
It works.

**Comment by SamPotts** [comment]
Awesome!

**Comment by espellcaste** [comment]
@SamPotts it's not that clear in the documentation that that's the way to go. I had the same problem on Windows and got me some 30 minutes to figure it all out!

**Comment by SamPotts** [comment]
I'll update the docs to make it more obvious. Thanks for the feedback fellas :+1:
