### ISSUE TITLE
Black line across bottom and sometimes side

### ISSUE THREAD

**Issue by danielrobertsdev** [Selz/plyr#531]
- [Can't see this issue in the list] Issue does not already exist
- [Don't think so] Issue observed on https://plyr.io

### Environment

- Browser: Chrome, Safari and Firefox
- Version:  
- Operating System: OS X El Capitan
- Version: 

Players affected:
- YouTube
- Vimeo

### Steps to reproduce 
-

**Comment by SamPotts** [comment]
There was a bug in Chrome 56 where HTML5 poster images seemed to render a black bar above and below some poster images. Seems to be fixed in 57. 

With the iframe embedded players, to allow them to be responsive a 16:9 aspect ratio is assumed. This is fairly standard practice given that's the most popular aspect ratio. HTML5 video will reflect the video's aspect ratio naturally. 

As such I'm not sure this is something I'll be able to fix in Plyr. 

FYI: the markdown `[]` render checkboxes and you just need to add an 'x' in the middle `[x]`

**Comment by danielrobertsdev** [comment]
Hi Sam,

Thanks for the quick reply, really appreciate it! Will update My browsers and see if it's still an issue.

Thanks for the heads on the mark down language, was a bit rushed yesterday and didn't get chance to look.

Many thanks,
Dan
