### ISSUE TITLE
Do Youtube video views count when embedded through Plyr?

### ISSUE THREAD

**Issue by georgegach** [Selz/plyr#556]
Loved Plyr a lot, but I wonder if Youtube views are accumulated through Plyr embed? 

I read even Youtube embed player declines views when autoplay is on. What's the situation with Plyr? Can anyone confirm that views (normal or autoplayed) count as legit?

I think views might not count simply because of this unresolved issue I couldn't find workaround for. 
> Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://www.youtube.com') does not match the recipient window's origin ('http://192.168.0.144').

**Comment by SamPotts** [comment]
Yep, they count. It's been raised before. All Plyr does is provide a custom UI for their embeds so while their embeds count plays for all types (they do) then you're all good. 

Autoplay won't work on iOS due to a restriction in Mobile Safari. 

That error is unrelated and is an error their side. Feel free to raise a bug over at YouTube although I've raised a few and got no where. They're fairly useless.

**Comment by georgegach** [comment]
Thanks for clearing that up so promptly!
