### ISSUE TITLE
plyr vs video.js

### ISSUE THREAD

**Issue by tomByrer** [Selz/plyr#60]
What are the difference between the 2 please?

Here is what I have so far:

* plyr is much smaller
* video.js has wider compatibility
* video.js has larger ecosystem (plugins, skins) since it has been around longer
* video.js is supported by a [large video company](https://www.brightcove.com/en/)
* video.js has [variable playback rate](https://github.com/videojs/video.js/blob/stable/docs/api/vjs.Player.md#playbackrate-rate-) (which I am most concerned about for a possible project)

**Comment by SamPotts** [comment]
Hey @tomByrer ,

The fundamental reason I wrote Plyr was because neither Video.js or MediaElement.js allowed me to write semantic, custom controls. At the time they used hacks like `<span>`  and `<a href="#">` as buttons which is just plain lazy. Even supporting IE7 is possible using the correct elements. I didn't support IE8 and 9 because the longer you support vintage browsers, the longer they stay around for. You have to break eggs to make an omelette as the saying goes. I really just wanted to write a simple layer/abstraction on top of the already pretty decent HTML5 player. I didn't really write Plyr to be "better" but perhaps giving people another option. If you need to support the older browsers then consider Video.js or MediaElement.js. 

Variable playback rate has been raised and should be relatively easy to write. I just need to think about the best way to incorporate some of these changes without the library becoming too bloated with features that only some people use. Variable play rate is super simple so would be a "core" feature. Things like playlists and Youtube or Vimeo playback would be add-ons to the core in my eyes. 

Just my 2c. I am totally happy to hear feedback on it.

**Comment by tomByrer** [comment]
> longer you support vintage browsers, the longer they stay around for

That is only true for the computer-savvy crowd, which is not the majority of people on the internet.  I think at least 20% of Windows users who have Fx or Chrome had a friend install it for them.  Alot of people don't even understand you need a 'client' to access the internet.

For my tool, I can force people to use the latest browsers.  For sharing video to my typical consumers, I can not.  But I do think you being a forward-thinking alternative is better, since I can use those other 2 players to ensure comparability.

Variable play as core (a few lines of code), & YouTube/Vimeo/specific source playback in an as-needed plugin is best.

cheers

**Comment by SamPotts** [comment]
You'll probably find that these days, it's corporate users that get stuck on old versions (from experience). Legacy systems make the upgrades more difficult. Most (if not all?) major browsers now self-update so the non computer savvy users barely notice anything has changed unless something they use frequently in the UI has changed. 

Like I say the playback speed itself is easy. The UI will probably take a little longer to do nicely. I also want to be able to make controls optional which I'd probably do at that stage.
