### ISSUE TITLE
Seeking doesn't work correctly when container positioned with negative translate2d

### ISSUE THREAD

**Issue by jakubmal** [Selz/plyr#65]
First of all, thanks for all the hard work you put in this project!

Here is the problem:
One way to center a div of unknown height/width is to use ```position:absolute;``` with ```transform: translate(-50%, -50%);```
Better described here: https://css-tricks.com/centering-percentage-widthheight-elements/

Say you have a modal, which is centered using this method, and you put a plyr-enhanced video inside.
Due to the fact that you use a simplified way of calculating progress bar offset (related to mouse click point), when seeking (click on a progress bar), a video starts playing at a wrong time - it simply doesn't respect ```transform: translate(-50%, -50%);```

PR may follow, but I usually use jQuery these days, and I don't want to contribute barely working code to your repo.

**Comment by SamPotts** [comment]
Hey Jakub,

Thanks! Are you using the latest version? I changed to use a range input rather than detect a click on the progress bar and calculate the offset. The change was partly for the reason you mentioned and partly for a better experience on touch devices. 

Maybe give that a go and let me know?

Cheers
Sam

**Comment by jakubmal** [comment]
Hey,
Ooops, my bad, I locked on 1.0.20. It's definitely fixed in the 1.0.26. Sorry!

**Comment by SamPotts** [comment]
No worries at all. If you find anything else let me know :+1:
