### ISSUE TITLE
Internet Explorer Captions

### ISSUE THREAD

**Issue by afemath** [Selz/plyr#71]
I have to create sites that are 508 compliant because I work on US government projects. They often insist that sites must be accessible on as many platforms as possible. This is especially true because government computers are often out of date (as far as browsers go anyway). I have been reviewing this media player on various internet explorer versions, I have noticed some issues.
- IE9 (wind7) - There are no captions, but the video plays
- IE10 (wind8) - There is a captions option, but it does not seem to work. I cannot get the captions to appear.

Are their any plans to solve these issues? If so, then I would really like to implement this player into various websites and maybe work on a Drupal module.

**Comment by SamPotts** [comment]
Hi @afemath , I was unaware of these issues. I will take a look. I'm sure it'll be an easy fix. 

Thanks :+1:

**Comment by SamPotts** [comment]
Hi @afemath, I've just had a look at this again but I can't seem to re-produce the errors with IE10? Plyr doesn't currently support IE9 because it doesn't support the `<progress>` element unfortunately. I was planning on adding support by detecting the presence of Lea Verou's polyfill (https://github.com/LeaVerou/HTML5-Progress-polyfill) but not sure what to do about `<input type="range">` since all the polyfill's are pretty gross for that.

**Comment by makshh** [comment]
Hi @SamPotts,

Maybe this plugin for IE9?
http://ionden.com/a/plugins/ion.rangeSlider/demo.html

**Comment by SamPotts** [comment]
Closing this as I don't plan to support IE9 and IE10 should be functioning.
