### ISSUE TITLE
Keyboard control of playback

### ISSUE THREAD

**Issue by calvintam236** [Selz/plyr#82]
I notice there are some control for the player using keyboard, like space bar and the enter can be used to control play/pause.

Is it possible to add other control and/or custom control for it?
E.g. Right arrow = fast forward, left arrow = rewind, up arrow = volume up, down arrow = volume down?

**Comment by SamPotts** [comment]
Hey @calvintam236 , this behaviour is already present but you need to be focused on the `<input type="range">` scrubber. I'd be hesitant to change the binding to be for the whole player since the left and right arrow keys also control the volume control. This is default browser behaviour which shouldn't really be changed on accessibility grounds. Keyboard users will be familiar which various inputs on HTML controls and changing them is generally not a good idea.
