### ISSUE TITLE
setVolume will get "Uncaught IndexSizeError" when set value below 0

### ISSUE THREAD

**Issue by calvintam236** [Selz/plyr#83]
Since there is no way to get the volume, if the value goes below 0, there will be an error.
```
Uncaught IndexSizeError: Failed to set the 'volume' property on 'HTMLMediaElement': The volume provided (-0.1) is outside the range [0, 1].
```

**Comment by SamPotts** [comment]
Hey @calvintam236 ,

Don't enter a value less than 0 :+1: heh, I'll put some handling in there for that. 

You can get the volume from the HTML element itself, but of course it's a floating point rather than the 0-10 range that plyr uses. 

`document.querySelector(".player").plyr.media.volume` would return `0.7` on plyr.io for example. 

I'll put some handling in for the out of bounds values.

**Comment by SamPotts** [comment]
Pushed a fix for this also improved how the player monitors volume/mute changes. Let me know if there's any problems :+1:

**Comment by calvintam236** [comment]
Hey @SamPotts, it seems when you set volume = 10 at setup with v1.1.8, the volume controls shows 0..

**Comment by SamPotts** [comment]
I've just pushed some tweaks in 1.1.9 but check your local storage value. The value of the volume is set in local storage (it's an option, defaulted to on) so when a user comes back, they get the same value. If you muted and refreshed, this would be 0.

Run this in your console:
`window.localStorage.plyr_volume`
If it returns 0, then that's why.

**Comment by calvintam236** [comment]
hey @SamPotts I don't think the issue was fixed. Try adding "volume: 10," at docs.js and visit your demo. The volume in the player shows at the bottom (but not mute). Get media.volume value is 1 using console.log.

**Comment by SamPotts** [comment]
Check 1.1.10 :+1: I think I've nailed it.

**Comment by calvintam236** [comment]
@SamPotts Fixed! Thank you! :+1:

**Comment by SamPotts** [comment]
No problem. I'll look at your suggestion for changing track by API asap too.
