### ISSUE TITLE
Support data URI sub tracks

### ISSUE THREAD

**Issue by calvintam236** [Selz/plyr#88]
Tried on my project embed track source in the data url format. Captions does not detect by the player. However, native runs the subtitle. (Cannot control hide/ show since caption is not detected)
Tested on Chrome, Opera. Not sure it occurs on Firefox or not.

![caption](https://cloud.githubusercontent.com/assets/6436149/7716168/dfc4773e-fe43-11e4-850f-5b29c80c060d.png)

**Comment by SamPotts** [comment]
You're using a data URI for the track source? That's pretty edge case. You're better off hosting them on a CDN and setting proper cache headers but I will look at this at some stage.

**Comment by calvintam236** [comment]
When the subtitle is that small, it saves time to have another request to
fetch the subtitle. Right now no control as shown on the screenshot.

**Comment by calvintam236** [comment]
@SamPotts I tested and found out why it does not load.
https://github.com/Selz/plyr/blob/master/src/js/plyr.js#L1030
It should not limit to only "captions". At the above test case, I did not set the kind. So this line should be:
```
if (kind === "subtitles" || kind === "captions") {
```
I am not sure if the kind attribute is not set, it will receive the default value or just blank. I am not expert in JS.

**Comment by SamPotts** [comment]
I've made a couple of changes which should resolve this I think. Thanks for doing some digging. :+1: 

You really should add the correct `kind` attribute to the `<track>` element though since captions and subtitles are different things. Plyr now supports both and treats them the same. 

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/track
