### ISSUE TITLE
Missing player icons.

### ISSUE THREAD

**Issue by Arcrammer** [Selz/plyr#91]
![screen shot 2015-06-02 at 13 03 55](https://cloud.githubusercontent.com/assets/8358956/7941859/10689124-0928-11e5-807d-22e7efc38f26.png)

I don't understand why this is happening. I've linked both `plyr.css` and `plyr.js` in my `head`.

**Comment by Arcrammer** [comment]
I was missing the AJAX call to load the icons. :)
```javascript
(function(d,p){
    var a=new XMLHttpRequest(),
        b=d.body;
      a.open("GET",p,!0);
      a.send();
      a.onload=function(){
      var c=d.createElement("div");
      c.style.display="none";
      c.innerHTML=a.responseText;
      b.insertBefore(c,b.childNodes[0])
  }
})(document,"/19.-WIA/The-Presentation/Assets/Plyr/dist/sprite.svg");
```

**Comment by SamPotts** [comment]
:+1:

**Comment by JosephSilber** [comment]
I'm having the same problem (using only audio), but I do fetch them over AJAX. I can even see the SVG in the document:

![image](https://cloud.githubusercontent.com/assets/1403741/11985700/8b04b134-a995-11e5-8d3d-88d9b3a63daa.png)

and I see the `xlink:href` is set up correctly:

![image](https://cloud.githubusercontent.com/assets/1403741/11985714/ac7fc8ee-a995-11e5-9c64-1d60cfe1cba2.png)

But the icons are simply not shown:

![image](https://cloud.githubusercontent.com/assets/1403741/11985727/d1a7aa6a-a995-11e5-8406-19619d0e3430.png)

I must be doing something wrong, but I have no idea what :disappointed:

**Comment by SamPotts** [comment]
It could well be a CSS issue, do you have a public page I could take a look at by any chance?

**Comment by JosephSilber** [comment]
While trying to create a reduced test-case for you, I found the problem.

My HTML document had a `base` tag, which somehow messed up the SVG link. I'm not sure why exactly, but that's what caused it.

For now I removed the `base` tag and it works. Do you know if there's any proper way around it?

**Comment by SamPotts** [comment]
Someone else has mentioned this recently so I'll look into a solution for users using the `base` tag.

**Comment by Ceremony64** [comment]
This can be fixed by prefixing the referenced id by the current location like so:
```javascript
'<svg><use xlink:href="' + window.location + iconPath + '-play" /></svg>'
```

I currently can't think of a reason why this change could break existing implementations.

P.S. Currently the basetag issue only seems to apply to Firefox. Chrome and IE seem to currently display the icons when I used the basetag "/". I didn't test other browser or how the mentioned browsers behave with a different basetag.

**Comment by SamPotts** [comment]
I'm not going to make that change globally though as it wouldn't work if the sprite is ajax'ed into the page elsewhere. In that case you just need `<use xlink:href="#icon-id">` - using external resources in tha attribute only works currently for same domain and not in all browsers.

**Comment by Ceremony64** [comment]
Once it is ajaxed in there, doesn't it always get appended to the current document for it to work with plyr? If so, it would still work. Maybe I'm missing/misunderstanding something here?

**Comment by SamPotts** [comment]
Not quite. The current recommended method of loading a sprite if you're using cross domain is to load in the sprite using the AJAX method into a hidden div on the page and then reference the elements in the sprite by id. For example:

```html
<svg><use xlink:href="#icon-example"></svg>
```

In an ideal world to save the hassle with loading via AJAX you would reference the path to the icons in the `<use>` element as you describe, either:

```html
<svg><use xlink:href="/path/to/sprite.svg#icon-example"></svg>
```

Or externally referenced:

```html
<svg><use xlink:href="https://cdn.com/path/to/sprite.svg#icon-example"></svg>
```

Unfortunately the second option isn't allowed due to cross domain issues (even adding `crossorigin` does nothing). I've catered for these options however by offering an `iconUrl` option in the config which will either load via AJAX if external or using the first method if relative: 
https://github.com/Selz/plyr#svg

So you could achieve what you're asking by specifying the URL to the sprite as the `iconUrl` option. 

You can see the `iconUrl` in action if you clone and run the repo locally and head to /demo - you'll notice the `xlink:href` attribute value has the path prefixed:

![image](https://cloud.githubusercontent.com/assets/719092/25256325/53d931a6-2673-11e7-9fb4-8fbe3bb3fbe7.png)
